urls:
  coinmarketcap:
      api: https://api.coinmarketcap.com
      files: https://files.coinmarketcap.com
      paths:
        ticker: /v1/ticker/
        images:
          coins:
            small: /static/img/coins/128x128/
            medium: /static/img/coins/128x128/
            large: /static/img/coins/128x128/
  etherscan:
    api: https://api.etherscan.io/api
    key: apiKey=J5CH6MQXE7VJGYJGEQRYSS1KJ319QJQY73
    query:
      modules:
        stats: module=stats
      actions:
        ethPrice: action=ethprice
